src/Entity/Boardgame.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\BoardgameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: BoardgameRepository::class)]
#[ApiResource()]
class Boardgame
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank(message: "Ce champ est obligatoire")]
    #[ORM\Column(length: 100)]
    private ?string $title = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $release_year = null;

    #[ORM\Column(length: 55)]
    private ?string $publisher = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column(length: 10)]
    private ?string $player_number = null;

    #[ORM\Column(length: 10)]
    private ?string $age = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $average_duration = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    /**
     * @var Collection<int, Category>
     */
    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'boardgames')]
    private Collection $categories;

    /**
     * @var Collection<int, Reviews>
     */
    #[ORM\OneToMany(targetEntity: Reviews::class, mappedBy: 'boardgame')]
    private Collection $reviews;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'boardgames')]
    private Collection $users;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getReleaseYear(): ?int
    {
        return $this->release_year;
    }

    public function setReleaseYear(int $release_year): static
    {
        $this->release_year = $release_year;

        return $this;
    }

    public function getPublisher(): ?string
    {
        return $this->publisher;
    }

    public function setPublisher(string $publisher): static
    {
        $this->publisher = $publisher;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPlayerNumber(): ?string
    {
        return $this->player_number;
    }

    public function setPlayerNumber(string $player_number): static
    {
        $this->player_number = $player_number;

        return $this;
    }

    public function getAge(): ?string
    {
        return $this->age;
    }

    public function setAge(string $age): static
    {
        $this->age = $age;

        return $this;
    }

    public function getAverageDuration(): ?int
    {
        return $this->average_duration;
    }

    public function setAverageDuration(int $average_duration): static
    {
        $this->average_duration = $average_duration;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }

    /**
     * @return Collection<int, Reviews>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Reviews $review): static
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setBoardgame($this);
        }

        return $this;
    }

    public function removeReview(Reviews $review): static
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getBoardgame() === $this) {
                $review->setBoardgame(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addBoardgame($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeBoardgame($this);
        }

        return $this;
    }

}

src/Form/BoardgameForm.php
<?php

namespace App\Form;

use App\Entity\Boardgame;
use App\Entity\Category;
use App\Repository\CategoryRepository;
use EasyCorp\Bundle\EasyAdminBundle\Config\Asset;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;

class BoardgameForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'constraints' => [
                new NotNull(['message' => "patate"]),
                new Length(['max' => 12]),
                ],
            ])
            ->add('release_year')
            ->add('publisher')
            ->add('picture', FileType::class, [
                'mapped' => false,
                'required' => false
            ])
            ->add('player_number')
            ->add('age')
            ->add('average_duration')
            ->add('description')
            // ->add('categories', EntityType::class, [
            //     'class' => Category::class,
            //     'expanded' => true,
            //     'multiple' => true
            // ])
            ->add('envoyer', SubmitType::class)
        ;
    }

    public function getAllCategories(CategoryRepository $cr)
    {
        $categories = $cr->findAll();
        return $categories;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Boardgame::class,
        ]);
    }
}

src/Controller/BoardgameController.php
<?php

namespace App\Controller;

use App\Entity\Boardgame;
use App\Form\BoardgameForm;
use App\Repository\BoardgameRepository;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\Routing\Attribute\Route;

final class BoardgameController extends AbstractController
{
    #[Route('/boardgame', name: 'app_boardgame')]
    public function index(): Response
    {
        return $this->redirectToRoute('app_boardgame_show', ['id'=>'1']);
    }

    #[Route('/boardgame/{id}', name: 'app_boardgame_show')]
    public function show($id, BoardgameRepository $boardgameRepository): Response
    {
        $boardgame = $boardgameRepository->find($id);
        //dump($boardgame);
        return $this->render('boardgame/show.html.twig', [
            'boardgame' => $boardgame
        ]);
    }

    #[Route('/boardgame/new', name: 'app_boardgame_new', priority: 2)]
    public function new(FileUploader $fileUploader, Request $request, EntityManagerInterface $em) : Response
    {
        $boardgame = new Boardgame;
        $form = $this->createForm(BoardgameForm::class, $boardgame);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            /** @var UploadedFile $pictureFile */
            $pictureFile = $form->get('picture')->getData();
            if ($pictureFile) {
                $pictureFileName = $fileUploader->upload($pictureFile);
                $boardgame->setPicture($pictureFileName);
            }else{
                $boardgame->setPicture('default.png');
            }
            $em->persist($boardgame);
            $em->flush($boardgame);
            return $this->redirectToRoute('app_home');
        }

        return $this->render('boardgame/new.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/boardgame/{id}/edit', name: 'app_boardgame_edit')]
    public function edit($id, FileUploader $fileUploader, Request $request, EntityManagerInterface $em, BoardgameRepository $bgr) : Response
    {
        $boardgame = $bgr->find($id);
        $form = $this->createForm(BoardgameForm::class, $boardgame);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            /** @var UploadedFile $pictureFile */
            $pictureFile = $form->get('picture')->getData();
            if ($pictureFile) {
                $pictureFileName = $fileUploader->upload($pictureFile);
                $boardgame->setPicture($pictureFileName);
            }
            $em->persist($boardgame);
            $em->flush($boardgame);
            return $this->redirectToRoute('app_home');
        }

        return $this->render('boardgame/edit.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/boardgame/{id}/delete', name: 'app_boardgame_delete')]
    public function delete($id, EntityManagerInterface $em, BoardgameRepository $bgr, KernelInterface $ki) : Response
    {
        $uploadDir = $ki->getProjectDir().'/public/uploads/'; 
        $boardgame = $bgr->find($id);
        $img = $boardgame->getPicture();
        if($img != 'default.png'){
            unlink($uploadDir.$img);
        }
        $em->remove($boardgame);
        $em->flush($boardgame);
        return $this->redirectToRoute('app_home');
    }

    #[Route('/boardgame/{id}/addtocollection', name: 'app_boardgame_addToCollection')]
    public function addToCollection($id, BoardgameRepository $br, EntityManagerInterface $em, Request $request)
    {
        /** @var App\Entity\User $user */
        $user = $this->getUser();
        $boardgame = $br->find($id);
        $user->addBoardgame($boardgame);
        $em->persist($user);
        $em->flush();
        
        // Si c'est une requête AJAX, retourner une réponse JSON
        if ($request->isXmlHttpRequest()) {
            return $this->json(['success' => true, 'message' => 'Jeu ajouté à votre collection']);
        }
        
        return $this->redirectToRoute('app_boardgame_show', ['id' => $id]);
    } 

    #[Route('/boardgame/{id}/removefromcollection', name: 'app_boardgame_removeFromCollection')]
    public function removeFromCollection($id, BoardgameRepository $br, EntityManagerInterface $em, Request $request)
    {
        /** @var App\Entity\User $user */
        $user = $this->getUser();
        $boardgame = $br->find($id);
        $user->removeBoardgame($boardgame);
        $em->persist($user);
        $em->flush();
        
        // Si c'est une requête AJAX, retourner une réponse JSON
        if ($request->isXmlHttpRequest()) {
            return $this->json(['success' => true, 'message' => 'Jeu retiré de votre collection']);
        }
        
        return $this->redirectToRoute('app_boardgame_show', ['id' => $id]);
    } 
}

templates/boardgame/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mettre à jour le jeu{% endblock %} 
{% block body %}
    <h1 class="my-3">Mettre à jour le jeu</h1>
    {{ form(form) }}
{% endblock %}

templates/boardgame/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un jeu{% endblock %} 
{% block body %}
    <h1 class="my-3">Ajouter un jeu</h1>
    {{ form(form) }}
{% endblock %}

templates/boardgame/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{boardgame.title}}{% endblock %} {# mettre le titre du jeu #}

{% block body %}
    <div class="row mt-5">
        <div class="col-12 col-md-3 me-5">
            <img src="{{ asset('uploads/' ~ boardgame.picture) }}" alt="{{boardgame.title}}">
        </div>
        <div class="col-12 col-md-8 px-5">
            <div class="row">
                <div class="col-6">
                    <h1>{{boardgame.title}}</h1>
                    <p>{{boardgame.publisher}}</p>
                    <small>{{boardgame.releaseYear}}</small>
                </div>
                <div class="col-6">
                    <h3 class="text-uppercase">informations : </h3>
                    <span class="text-info me-2"><i class="fa-solid fa-users fa-2x"></i></span>{{boardgame.playerNumber}} |
                    <span class="text-success mx-2"><i class="fa-solid fa-cake-candles fa-2x"></i></span>{{boardgame.age}} |
                    <span class="text-danger mx-2"><i class="fa-solid fa-clock fa-2x"></i></span>{{boardgame.averageDuration}}m
                </div>
            </div>
            <div class="mt-3">
                <h3 class="text-uppercase">description : </h3>
                <p>{{boardgame.description | striptags }}</p>
            </div>
            <div class="mt-3">
                {% if (app.user) %}
                    {# Composant de gestion de collection #}
                    <div {{ stimulus_controller('collection', {
                        boardgameId: boardgame.id,
                        isInCollection: app.user.boardgames.contains(boardgame),
                        addUrl: path('app_boardgame_addToCollection', {id: boardgame.id}),
                        removeUrl: path('app_boardgame_removeFromCollection', {id: boardgame.id})
                    }) }} class="mb-3">
                        <button type="button" 
                                class="btn btn-lg"
                                data-collection-target="button"
                                data-action="click->collection#toggle">
                            <i class="fas" data-collection-target="icon"></i>
                            <span data-collection-target="text"></span>
                        </button>
                    </div>
                    <turbo-frame id="reviews.{{ boardgame.id }}">
                        <a href="{{ path('app_review_new', {id: boardgame.id}) }}" class="btn btn-primary my-3">Rédiger un avis</a>
                    
                {% endif %}
                <h3 class="text-uppercase">Avis de la communauté : </h3>
                
                {% for review in boardgame.reviews %}
                <span class="heading3">
                    {{ review.rating }}/5
                </span>
                <figure>
                    <blockquote class="blockquote">
                        <p>{{ review.commentary }}</p>
                    </blockquote>
                    <figcaption class="blockquote-footer">
                        {{ review.user.pseudo }}
                    </figcaption>
                </figure>
                {% endfor %}
                </turbo-frame>
            </div>
        </div>
    </div>
{% endblock %}